from .Catboost_Bagging_Generator import Catboost_Bagging_onnx_generator
from .Fastai_Bagging_Generator import fastai_onnx_generator
from .LightGBM_Bagging_Generator import LightGBM_Bagging_onnx_generator
from .NeuralTorch_Bagging_Generator import NeuralTorch_BAG_onnx_generator
from .RandomForest_Bagging_Generator import RandomForest_Bagging_Onnx
from .Weighted_Ensemble_Generator import Weighted_ensemble_onnx_generator
from .XGboost_Bagging_Generator import XGboost_bagging_onnx_generator

NeuralTorch_Bagging_onnx_generator = NeuralTorch_BAG_onnx_generator
RandomForest_Bagging_onnx_generator = RandomForest_Bagging_Onnx
Weighted_Ensemble_onnx_generator = Weighted_ensemble_onnx_generator
XGboost_Bagging_onnx_generator = XGboost_bagging_onnx_generator
Fastai_Bagging_onnx_Generator = fastai_onnx_generator
LightGBM_Bagging_onnx_Generator = LightGBM_Bagging_onnx_generator
Catboost_Bagging_onnx_Generator = Catboost_Bagging_onnx_generator